### ISSUE TITLE
Error in Starting the Project

### ISSUE THREAD

**Issue by Mohtadrao** [jyp-studio/Invoice_detection#2]
It is giving "path not found or network error" scenario when giving the path of the invoice images and starting it.

**Comment by Howeng98** [comment]
Hi @Mohtadrao , do you solve the problem?  I also encounter same issue.

**Comment by Mohtadrao** [comment]
No it was not working so I had to train my own model using the base donut model.
Using this repo
https://github.com/clovaai/donut
